name: waves_model2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=2.0.2
  - numba=0.60.0
  - joblib=1.4.2
  - seaborn=0.13.2
  - qtpy=2.4.2
  - pyvistaqt=0.11.1
  - cmocean=4.0.3
  - colorcet=3.1.0
  - imageio=2.36.1
  - h5py=3.12.1
  - nibabel=5.3.2
  - mne=1.9.0
  - pip
  - pip:
    - pyqt6
